// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twvybgvokbqccsiaoujz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dnliZ3Zva2JxY2NzaWFvdWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDIxMjIsImV4cCI6MjA2NDYxODEyMn0.nwkVaY9xcKSInz-epvM4RUra0lHXGCefWJwIvJPn1Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);